import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layouts/Header";
import Footer from "@/layouts/Footer";
import { navList } from "@/global/base";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative overflow-x-hidden`}>
        <Header navList={navList} />
        <main className="bg-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
